/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_orangepi_api_I2cControl */

#ifndef _Included_com_example_orangepi_api_I2cControl
#define _Included_com_example_orangepi_api_I2cControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CReadReg8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CReadReg8
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CReadReg16
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CReadReg16
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CWriteReg8
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CWriteReg8
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CWriteReg16
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CWriteReg16
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_orangepi_api_I2cControl
 * Method:    wiringPiI2CSetup
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_I2cControl_wiringPiI2CSetup
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
