/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_orangepi_api_GPIOControl */

#ifndef _Included_com_example_orangepi_api_GPIOControl
#define _Included_com_example_orangepi_api_GPIOControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_orangepi_api_GPIOControl
 * Method:    doExport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_GPIOControl_doExport
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_orangepi_api_GPIOControl
 * Method:    setGpioDirection
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_GPIOControl_pinMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_orangepi_api_GPIOControl
 * Method:    readGpioStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_GPIOControl_digitalRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_orangepi_api_GPIOControl
 * Method:    writeGpioStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_GPIOControl_digitalWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_orangepi_api_GPIOControl
 * Method:    unexportGpio
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_GPIOControl_doUnexport
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
