/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wiringop_wpiControl */

#ifndef _Included_com_example_wiringop_wpiControl
#define _Included_com_example_wiringop_wpiControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiSetup
  (JNIEnv *, jclass);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    pinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_pinMode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    pullUpDnControl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_pullUpDnControl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_digitalRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_digitalWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiSPIGetFd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiSPIGetFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiSPIDataRW
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiSPIDataRW
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiSPISetupMode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiSPISetupMode
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiSPISetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiSPISetup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_serialOpen
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_serialClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialFlush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_serialFlush
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialPutchar
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_serialPutchar
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialPuts
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wiringop_wpiControl_serialPuts
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialDataAvail
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_serialDataAvail
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    serialGetchar
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_serialGetchar
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CReadReg8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CReadReg8
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CReadReg16
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CReadReg16
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CWriteReg8
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CWriteReg8
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CWriteReg16
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CWriteReg16
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_example_wiringop_wpiControl
 * Method:    wiringPiI2CSetup
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_wiringop_wpiControl_wiringPiI2CSetup
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
